services:

  frontend_service:
    build: ./frontend_service
    ports:
      - "7860:7860"
    volumes:
      - ./frontend_service:/app
    networks:
      - app_network

  data_management_service:
    build: ./data_management_service
    ports:
      - "8001:8001"
    volumes:
      - ./data_management_service:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8001 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://user:password@db:5432/appdb
    depends_on:
      - db
    networks:
      - app_network

  disease_predictor_service:
    build: ./disease_predictor_service
    ports:
      - "8002:8002"
      - "5000:5000" # MLFlow
    volumes:
      - ./disease_predictor_service:/app
    restart: always
    command: uvicorn main:app --host 0.0.0.0 --port 8002 --reload
    networks:
      - app_network

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=appdb
    ports:
      - "5432:5432"
    restart: always
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge